### PR TITLE
Changes the onchange event to oninput

### PR DESCRIPTION
**Pull request by zwrawr**
a fix for #309.
The oninput event only sets a state.

### CODE REVIEW

**Comment by povrazor** [comment]
Ok.

**Comment by povrazor** [comment]
Activate dialog is fixed, but password reset is broken now.

**Comment by zwrawr** [comment]
oops, i forgot i removed those brackets. Should be fixed now.

**Comment by povrazor** [comment]
Ah shoot, I merged it in to my own branch, but I'm not quite ready to push that to the live server.

**Pull request merged**
