### PR TITLE
Open Externally button - Issue #486

### PR DESCRIPTION
**Pull request by StormBurpee**
Adds a button next to the stream info in the bottom, for opening in a new tab
Proposes a fix for #486 

image

### CODE REVIEW

**Comment by StormBurpee** [comment]
Accidentally added a commit I meant for a separate pull request here... Forgot to create another branch sorry about that, but this was in terms of adding a temporary logout button, until you did the whole drop down thing for the user. Issue #285

**Comment by povrazor** [comment]
I think the 'open externally' button needs to look distinct. The rounded look is the same as the metrics, which are just metrics.

I'm not sure what I was thinking when I made my notes in #486, but what I would probably do is make the button invisible, but when you're hovering over the TV widget, just as play button lights up, a secondary icon becomes visible in the lower right corner (`/www/icons/icomoon/enlarge.svg'). If you then choose to hover over that icon, that lights up instead of the play button.

With the words "Open Externally", it looks somewhat cluttered. Opening externally shouldn't be a common thing, but like #486 is something that's desirable design wise for embeds.

**Comment by povrazor** [comment]
Also, while I appreciate the whitespace fixes, the shear amount of them makes it tricky to see which changes are whitespace and which are the proposed fixes.

**Comment by povrazor** [comment]
As for the temporary logout button, the problem is the nav bar gets cluttered on mobile. So yes a temporary button can work, but once I let people sign up for the upcoming event, certain mobiles will show 4 icons wide and no longer fit.

Is it better than nothing?... Ha, I can't decide. :smile:

That's actually part of the reason put `<DropDownUser>` down for now, as though I could easily make a hover menu, I needed something that could work on Mobile (i.e. unrolled needs to be state, not parent hover trickery). 

I like that you changed `Fetch.Post` to a `Fetch.Get`, but I think `Fetch.Get` omits credentials by default ... or at least it should (if `{}` evaluates to true, then it's working by accident). Off the top of my head, the `{}` should be replaced with a `true`, but I would double check `src/shrub/internal/fetch` (or wherever it is... something like that).

**Pull request closed without merging**
