### PR TITLE
Screenshot Aspect Ratio - Fixes #362

### LINKED ISSUE #362: TV: Set minimum dimensions for screenshot
missingstream

This will likely require some hackery, such as this.

http://stackoverflow.com/questions/12121090/responsively-change-div-size-keeping-aspect-ratio

I forget what I did to fix the dynamically sized Calender, but do that.

### PR DESCRIPTION
**Pull request by StormBurpee**
Proposes a fix for setting the aspect ratio of the screenshot, whilst an image is loading 
Fixes #362 

image

### CODE REVIEW

**Comment by povrazor** [comment]
Cool. Have you tested it when the sidebar resizes? i.e. when you make the window less wide, things in the sidebar actually get smaller. The calender, the TV widget, etc.

**Comment by StormBurpee** [comment]
Yes, it's set to a constant 16:9 ratio, which is determined by the width of the container. It'll auto resize :smile:

**Comment by povrazor** [comment]
Ah, it looks like that introduced a new bug.

brokenborder

The main screenshot now breaks the border.

After undoing the change:

fitted

**Comment by StormBurpee** [comment]
Sorry, I didn't see that, give me a minute

**Pull request merged**
