### PR TITLE
Fixed image overlap and sizing 

### PR DESCRIPTION
**Pull request by StormBurpee**
This is better now
image
image

### CODE REVIEW

**Comment by povrazor** [comment]
Looks like the height is wrong. Notice how far away the Twitch Name+Icon is from the bottom in your examples above, compared to this:

fitted

**Comment by StormBurpee** [comment]
image
image

**Comment by StormBurpee** [comment]
actually

**Comment by povrazor** [comment]
yeah

**Comment by StormBurpee** [comment]
The detail is too far down

**Comment by povrazor** [comment]
We're on the same wavelength now. :smile:

**Comment by StormBurpee** [comment]
image
Does that look better?
I don't know, that right quote looks off to me, but I swear I haven't touched it

**Comment by StormBurpee** [comment]
Oh, is the height not dynamic and you've just set it to two lines high?

**Comment by StormBurpee** [comment]
Which, interestingly depending on how you want that part to be designed, could be brought up in an issue?

**Comment by povrazor** [comment]
Yeah, it's max 2 lines of description/title, since one was never enough, and some people tend not to have restraint.

**Comment by StormBurpee** [comment]
Well regardless, it should be fixed now!

**Comment by povrazor** [comment]
Oh interesting, `calc`. I'm guessing that was the reason you were pleased about IE 11?

**Comment by StormBurpee** [comment]
Exactly!

**Pull request merged**
