### PR TITLE
Fixes to notification code

### PR DESCRIPTION
**Pull request by sgstair**
May add some more later - I'm debugging the notifications page code which may have some issues with anonymous comments, but I need to finish some other things first.

### CODE REVIEW

**Comment by local-minimum** [comment]
I wish the linter would complain about things not defined and things imported and not used... thanks for finding it

**Comment by sgstair** [comment]
I suspect neither you nor pov saw this because it corresponds to a file that was deleted - so you'd only see this error on a clean rebuild.

**Comment by local-minimum** [comment]
yeah, linter could have complained about that the import wasn't used

**Comment by zwrawr** [comment]
Hit this issue as well, this fix is needed to build the source from scratch.

**Pull request merged**
