### PR TITLE
Handling not geting votes data in more graceful way

### PR DESCRIPTION
**Pull request by local-minimum**
Can build, but I can't test given current state and tricky because server also needs to not respond with data.

### CODE REVIEW

**Comment by local-minimum** [comment]
Added handling of not connecting to server for final results too. Again, can't really test beyond `make`.

**Comment by povrazor** [comment]
Sorry for the delay. Can you explain what it's supposed to do? Always a bit reluctant about untested code. ;)

**Comment by local-minimum** [comment]
Hard to remember now, but I think that when there was some issue with the site last event all of the sudden the game-page said "You don't have the votes" even if you had the vote, when the issue was really "Site isn't responding at the moment". I think this is was trying to differentiate those two.

**Comment by povrazor** [comment]
Riiiiiight. That does ring a bell.

**Comment by sgstair** [comment]
This is probably no longer necessary, as the underlying bug is fixed, and nodes should always have scores.

**Pull request closed without merging**
