### PR TITLE
Fixes the bug on platform dropdown

### LINKED ISSUE #1620: Previewing a game with tags removes tags
https://twitter.com/morphinestudio/status/988129616492613632

### PR DESCRIPTION
**Pull request by local-minimum**
Now it does update states and props on change properly in a relevant way.

Changes persists to preview mode and back.

Resolves #1620 and #1628

### CODE REVIEW

**Comment by mikekasprzak** [comment]
I get one of these when I edit my game in my VM.

```js
Potentially unhandled rejection [1] TypeError: Cannot read property '0' of undefined
    at ContentCommonBodyLink.render$$1 [as render] (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:18293:76)
    at renderComponent (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:4900:24)
    at rerender (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:4303:19)
    at tryCatchReject (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:4075:30)
    at runContinuation1 (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:4034:4)
    at Fulfilled.when (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:3822:4)
    at ContinuationTask.run (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:3932:24)
    at Scheduler._drain (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:2989:19)
    at Scheduler.drain (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:2954:9)
    at MutationObserver.run (http://ludumdare.org/-/all.debug.js?v=4240-9fa63bb6:3160:4)
```

**Comment by local-minimum** [comment]
I'll look into it. But that was strange... It shouldn't have worked for me if I got that. Could you detail how you edited? Like stepwise what you did?

**Comment by mikekasprzak** [comment]
I simply opened up my game attached to my account (clicked edit) and the
error pops up in the console. The game is nearly blank if I recall, just
has source code (which due to a design flaw might not have any meta data
for it because source code is currently implied if not specified). Visual
result is I have no links with this patch, instead of 1.

**Comment by local-minimum** [comment]
Oh I didn't get the error because I had a link and was just editing. I'll try and fix it on the train tomorrow. I can reproduce it so it is hopefully something simple.

**Comment by local-minimum** [comment]
Fixed the bug you reported, also added the hamburger icon to when the dropdown defaults (if it doesn't find the selected value and takes the first)

**Pull request merged**
