### PR TITLE
Adds acceesskeys to slaughter page for easier theme slaughtering.

### PR DESCRIPTION
**Pull request by balohmatevz**
"a" for good
"s" for slaughter
"d" for bad

### CODE REVIEW

**Comment by povrazor** [comment]
I'm reluctant to merge this, as elsewhere the shortcut keys are the arrow keys (which are currently broken due to another bug).

**Comment by balohmatevz** [comment]
While that's a better solution, this one can carry us through the period when the bug exists, as I'm sure there are other, much more pressing issues to fix than theme slaughter hotkeys. I added the accesskey to the code via the F12 console and it works great. 

So as a temporary fix, it works, and if it ends up being a permanent fix that's fine too, as having accesskeys is, while imperfect, still better than not having any hotkeys.

**Comment by povrazor** [comment]
Thing is, I don't even use QWERTY. While WASD is good idea, they key choices are not international keyboard friendly.

**Comment by balohmatevz** [comment]
Accept, slaughter, decline!

**Comment by karai17** [comment]
What about multiple sets of keys? ASD + <v> + 123?

**Comment by povrazor** [comment]
I'm not sure actionkeys (the feature proposed in the fix) supports more than 1 key.

**Comment by balohmatevz** [comment]
I maintain the "It's better than nothing, even if imperfect" opinion.

**Comment by povrazor** [comment]
Well come back to this later. #343

**Pull request closed without merging**
