### PR TITLE
Using checkboxes for item edit

### PR DESCRIPTION
**Pull request by local-minimum**
image

# Related Issues

* #1657 Is resolved by this

### CODE REVIEW

**Comment by mikekasprzak** [comment]
Ha! This is not exactly what #1657 is about (the issue is that posting anonymously is a separate publish button, and that clutters space), but hey, this seems a decent change too. :+1:

**Comment by mikekasprzak** [comment]
Looks like the shown state of the out-out checkboxes might be backwards. Before pulling your patch, I opted out of "Complexity", and after the upgrade my state became this:

screenshot from 2018-06-06 13-28-24

**Comment by local-minimum** [comment]
I'll check it I missed something.

**Comment by local-minimum** [comment]
As commit message said, there was some complexity in how the opt out data was prepared I didn't understand why, so I removed it and now it works.

**Pull request merged**
