### PR TITLE
Try #2 at Issue #486

### PR DESCRIPTION
**Pull request by StormBurpee**
*fingers crossed*
Hahah, okay, so I tried to understand better what you wanted, I closed the last pull request because it was a bit messy :worried:

- Used the SVGIcon
- Only displays on hover over active stream
- Play button loses its hover affect, when hovering over the external button

**Also, I'm so sorry, I don't know what I did, but it displayed so many whitespace changes... I'm so sorry** 
I think maybe its Atom? idk

E.g. :

image image image

### CODE REVIEW

**Comment by StormBurpee** [comment]
erm, https://github.com/ludumdare/ludumdare/pull/540/files?w=1 that link shows it without whitespace changes :relieved:

**Comment by povrazor** [comment]
Great. I like what I'm seeing. That `?w=1` feature is awesome.

One question: I'm curious why you need the `openExternal` variable?

**Comment by StormBurpee** [comment]
The ```openExternal``` variable is there, so it prevents the onClick from happening in the ```.-active``` element.

Both events get triggered from the click, the ```.-external``` gets triggered first, then the jammertv click gets triggered. without the variable, the jammer tv window still opens, and twitch opens in a new tab

**Comment by povrazor** [comment]
Okay. I thought so.

Try adding an `e.preventDefault();` call to the end of your function. In theory that should have the same effect.

**Comment by povrazor** [comment]
Ah sorry, looks like merging #538 made a small conflict too (probably whitespace, but I haven't looked).

**Comment by StormBurpee** [comment]
Give me a minute!

**Comment by StormBurpee** [comment]
```stopPropagation()``` did the trick, I'll push the update nowish

**Comment by StormBurpee** [comment]
Alright there we go!

**Comment by povrazor** [comment]
I pushed a funny button here on GitHub to collapse both merges in to a single merge. Let me know if it made things weird on your end at all.

**Comment by StormBurpee** [comment]
I think everything is fine?

**Comment by povrazor** [comment]
If you noticed nothing, then nothing is wrong. :smile:

**Pull request merged**
