### PR TITLE
Remember password

### PR DESCRIPTION
**Pull request by JonesAndrew**
https://github.com/ludumdare/ludumdare/issues/1501

The diff is a little messed up, but all I did was put the inputs into a form. I'm pretty sure this is mandatory for safari and firefox to recognize the fields.

### CODE REVIEW

**Comment by local-minimum** [comment]
lgtm, and welcome to the dev-team :) Did you try it out locally too with setting up vagrant and such?

**Comment by JonesAndrew** [comment]
Thanks. Ya, I followed all the steps and set up the vagrant. I was able to test out safari and that looked good, but I always forget how you trick firefox into letting you save passwords over HTTP.

**Comment by mikekasprzak** [comment]
Okay, I've pushed the change to the live server. Can someone with Safari confirm it's working? I've confirmed with Chrome that it didn't break anything.

As for Firefox, I might have a solution a bit later. Firefox for me complains that it doesn't want to offer to save passwords because of HTTP. That said, I might actually be able to get HTTPS working locally, it's just a little wonky to set up.

**Comment by JonesAndrew** [comment]
It worked for me on safari, but not on firefox.

**Comment by mikekasprzak** [comment]
Ah well, that's still an improvement. Thanks for the change. :)

**Pull request merged**
