### PR TITLE
Copy short link button

### LINKED ISSUE #1788: Implement a way to use ldj.am
Similar to this awesome firefox extension: https://addons.mozilla.org/en-US/firefox/addon/ld-shortlinkener/

### PR DESCRIPTION
**Pull request by zwrawr**
Closes #1788 

## Features
Adds button at the end of post titles. This only shows when on the post's page and not on the main feed.   
image

When clicked this copies the correct short link to clipboard. If successful the icon is replaced with a  :heavy_check_mark: for two seconds. If it fails the icon changes to :negative_squared_cross_mark: .
Screenshot from 2019-06-02 15-34-52

Copy to clipboard functionality from https://gist.github.com/lgarron/d1dee380f4ed9d825ca7 we might want to use https://github.com/lgarron/clipboard-polyfill if this simple solution is too buggy but so far it works well.

## Issues
- [x] ~~Not sure how to get the correct shortener link form js, it only appears to be defined in PHP, but not in the section where PHP constants are copied to js. See the below links for those files.~~
  
 https://github.com/ludumdare/ludumdare/blob/e7c1dc6b8d155e774d454374898bfb8a7574203c/src/public-url.redirect/main-redirect.php#L15
    https://github.com/ludumdare/ludumdare/blob/e7c1dc6b8d155e774d454374898bfb8a7574203c/src/main/main.php#L64

~~I'm not sure how to add a constant for the correct link shortener (ldj.am vs url.ludumdare.org). [this section of js](https://github.com/ludumdare/ludumdare/compare/master...zwrawr:short-link-button?expand=1#diff-d93231edb9fe5368a7151a230625e2f9R58) needs updating with the correct shortener URL.~~
  
------------------------------------
- [ ] Not tested on ie (see #1821) or mobile browsers (works on chrome, firefox, edge41 and opera)

### CODE REVIEW

**Comment by local-minimum** [comment]
Does the first state with the chain image say copy to clipboard on hover? Otherwise it might be a bit magical and vague what is happening. In general I think it would be best with a temporary tooltip that says "Short link copied to clipboard" and a negative message for failing.

**Comment by zwrawr** [comment]
Whoops, I totally forgot about messages because I was messing with having a card slide into the bottom. Before I decided that should be its own thing.
infocard

I'll get on adding them.

**Comment by zwrawr** [comment]
I've added tooltips with different messages depending on the state and a way to override the "IDEL" tooltip.

**Comment by mikekasprzak** [comment]
> Not sure how to get the correct shortener link form js, it only appears to be defined in PHP, but not in the section where PHP constants are copied to js. See the below links for those files.

I would do basically the same thing seen in `ludumdare/src/main/main.php` for the static domains. It has a little lookup table of domains with matching URL shorteners, then a couple lines later does a lookup.

**Comment by zwrawr** [comment]
I've done what you suggested and it seems to work.

**Pull request merged**
