### PR TITLE
Restricts some comment behaviour + bonus

### PR DESCRIPTION
**Pull request by local-minimum**
ld_comment_nolinks
(Post above in gif is by the same author as the one writing in the gif)

Gives feedback / hides submit buttons if:

1. Duplicating last posted comment (valid for all pages)
2. Posting url to your most recent authored post (this could probably be made more exact in pointing to most recent game for all makers on the game)

Exceptions to 2.:
* This only is a limit on games
* You are allowed to post whatever if you are one of the authors of the post.

And as a bonus, it might solve comment at-name autocomplete for those with more complex names.

Deals with issues #1636 #1625

### CODE REVIEW

**Comment by zwrawr** [comment]
I against stopping people from linking to there game.
The vast majority of people that link to their game are not being malicious, it seems unfair to stop them because a very small number of people are spamming.

Here's an example of a legitimate use https://ldjam.com/events/ludum-dare/41/ludum-dare-41-placeholder-1/post-your-games-for-me-to-rate , and there are many of these threads.

There is going to be backlash if you stop people linking to there games.

**Comment by local-minimum** [comment]
Link stopping was restricted to only be on other people's games. Not on posts for exactly that reason. @zwrawr do you still think that's bad then?

**Comment by mikekasprzak** [comment]
Can we get the auto complete fix isolated to it's own PR? I got yet another report of the autocomplete problem today.

**Comment by local-minimum** [comment]
@mikekasprzak I think those changes are isolated to https://github.com/ludumdare/ludumdare/pull/1639/files#diff-f2d8e3005d0a2d9ba2c416c60bf7b0e9 but you should build and test it locally. I didn't have any usernames that would match the problem, but the fix seemed reasonable.

**Pull request closed without merging**
