### PR TITLE
Created LoveButton component

### LINKED ISSUE #460: Post refreshes when <3'd
This means that embedded media will reset!

### PR DESCRIPTION
**Pull request by Ulydev**
Fixes #460

### CODE REVIEW

**Comment by Ulydev** [comment]
Just realised it fixes #458 as well. There's no *if* check for the user anymore, which means the website will detect if the user has already loved a post.

**Comment by zwrawr** [comment]
I get these errors on this branch.
http://prntscr.com/dh1512

**Comment by zwrawr** [comment]
Now preforms a client side check to see if the user is logged in before they love a post. If they are not logged in then they are moved to the secure site and the login window is popped up.

**Comment by Ulydev** [comment]
OK, it's all good now. Fixes #460 and #458

**Comment by zwrawr** [comment]
No Longer preforms a client side check to see if the user is logged in before they love a post.

**Comment by Ulydev** [comment]
According to https://github.com/ludumdare/ludumdare/issues/458#issuecomment-265855669 , #458 is not an issue. Now this PR fixes only #460

**Pull request merged**
